project:
  type: website

website:
  title: "Blog"
  navbar:
    right:
      - href: https://madhav-kanda.github.io/
        text: Home

format:
  html:
    theme: litera
    css: styles.css

execute:
  freeze: True



